import { Product } from './types/Product';

export const sampleProduct: Product[] = [
  {
    name: 'TV 1',
    slug: 'tv1',
    image: 'string',
    category: 'Digital Home',
    brand: 'LG',
    price: 2600,
    currency: '$',
    stockCount: '10900',
    descriptions: '55" QLed new tv brand',
    rating: 4,
    reviews: 10,
  },
  {
    name: 'TV 2',
    slug: 'tv2',
    image: 'string',
    category: 'Digital Home',
    brand: 'SAMSUNG',
    price: 3000,
    currency: '$',
    stockCount: '400',
    descriptions: '75" QLed new tv brand',
    rating: 5,
    reviews: 14,
  },
  {
    name: 'TV 3',
    slug: 'tv3',
    image: 'string',
    category: 'Digital Home',
    brand: 'TLC',
    price: 500,
    currency: '$',
    stockCount: '1000',
    descriptions: '46" QLed new tv brand',
    rating: 3,
    reviews: 22,
  },
  {
    name: 'TV 4',
    slug: 'tv4',
    image: 'string',
    category: 'Digital Home',
    brand: 'TLC',
    price: 550,
    currency: '$',
    stockCount: '1200',
    descriptions: '50" QLed new tv brand',
    rating: 1,
    reviews: 23,
  },
];
